CREATE DATABASE FISCAL;

CREATE TABLE NotaFiscal (
idNota SERIAL PRIMARY KEY,
Emissor VARCHAR (150)
Data TIMESTAMP UNIQUE NOT NULL
);


CREATE TABLE TabelaItem (

idNota SERIAL REFERENCES NotaFiscal (idNota)
idItem SERIAL PRIMARY KEY
Produto VARCHAR(150) UNIQUE  NOT NULL
Valor numeric(15, 3)
)